version: '3.4'

services:
  onlineenterpriseorders.web:
    image: ${DOCKER_REGISTRY-}onlineenterpriseordersweb
    build:
      context: .
      dockerfile: OnlineEnterpriseOrders.Web/Dockerfile

  onlineenterprisecategories.web:
    image: ${DOCKER_REGISTRY-}onlineenterprisecategoriesweb
    build:
      context: .
      dockerfile: OnlineEnterpriseCategories.Web/Dockerfile

  onlineenterpriseproducts.web:
    image: ${DOCKER_REGISTRY-}onlineenterpriseproductsweb
    build:
      context: .
      dockerfile: OnlineEnterpriseProducts.Web/Dockerfile

  onlineenterprise.identityserver:
    image: ${DOCKER_REGISTRY-}onlineenterprise.identityserver
    build:
      context: .
      dockerfile: OnlineEnterprise.IdentityServer/Dockerfile